# Generated by Django 5.2 on 2025-04-26 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='event',
        ),
        migrations.DeleteModel(
            name='NewsItem',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='family',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
